### ISSUE TITLE
Is it possible to use metrics/plots/data from the local S3-compatible storage?

### ISSUE THREAD

**Issue by Benjamin-Etheredge** [iterative/studio-support#1]
The current studio seems to only support AWS s3. Support for other s3-compatible APIs (like minIO) would be awesome.

**Comment by jorgeorpinel** [comment]
Q: If you setup an S3-compatible storage manually/locally (via https://dvc.org/doc/command-reference/remote/add) will Studio pick it up? Or any remote for that matter

**Comment by shcheklein** [comment]
Only if it's accessible from the machines that run Studio. If it's under firewall, NAT, local IP - etc, there is no way we can access it. Some proxy is required then.

Benjamin had a good point about saving at least certain artifacts into some externally accessible remotes, but that would ideally require some DVC support on the https://github.com/iterative/dvc/issues/4040 . @Benjamin-Etheredge feel free to chime in that ticket.

**Comment by jorgeorpinel** [comment]
> Only if it's accessible from the machines that run Studio.

I see. And MinIO is usually run in a local machine or network, right?

@Benjamin-Etheredge as a workaround for now you could try something like [Ngrok](https://ngrok.com/docs#tcp) or [Traefik](https://doc.traefik.io/traefik/) ([article](https://itnext.io/deploy-on-premise-s3-storage-using-qnap-nas-minio-and-traefik-bccbfefe511d)) to expose the local Minio service to the Internet (free, I think) — not sure about possible throughput limits.

**Comment by Suor** [comment]
Besides Minio there are cloud alternatives too. Anything DVC already works with should work in Studio too, using same settings and credentials.

**Comment by jorgeorpinel** [comment]
> Anything DVC already works with should work in Studio too

I think the key word in the issue title is "local". In that case Studio won't work with the (local) storage since it's not local or even available to Studio.

But yeah I don't suppose we're trying to solve that, which is a networking situation really. So Idk if this issue is actionable.

**Comment by jorgeorpinel** [comment]
But yeah I don't suppose we're trying to solve that which is a networking situation really. So Idk if this issue is actionable.

**Comment by ivyleavedtoadflax** [comment]
Maybe I misunderstood, but will studio read metrics from S3 out of the box? So far I've set all my metrics to `cache=false` so it has been reading them from github, but would be great if it could read them from S3

**Comment by shcheklein** [comment]
@ivyleavedtoadflax yes, it can read them from S3, so you can set `cache=true` and add credentials via Studio UI. Please give it a try, let us know if something doesn't work for you.

**Comment by ivyleavedtoadflax** [comment]
> @ivyleavedtoadflax yes, it can read them from S3, so you can set `cache=true` and add credentials via Studio UI. Please give it a try, let us know if something doesn't work for you.

Works great 👍

**Comment by Suor** [comment]
Do we plan to do something about it? And what can we do really? Or we simply keeping this for informational pruposes?

**Comment by shcheklein** [comment]
Let's keep it as a feature request for now.

**Comment by shcheklein** [comment]
Studio can be installed on-prem per request. Please reach us directly if there is a need. Closing this.
