### ISSUE TITLE
Selected columns change when I open a new PR

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [iterative/studio-support#10]
I have a very large number of metrics that I filter down to 12 using the tracking scope (those that contain the word weighted):
 
![image](https://user-images.githubusercontent.com/4583655/121259363-04638e80-c87e-11eb-95a2-953fb9bba2a9.png)

However, sometimes I see columns in the view which are not selected in the tracking scope. 

![image](https://user-images.githubusercontent.com/4583655/121259543-4260b280-c87e-11eb-8701-7b04f72ef11c.png)

I remove them in the columns menu, but after every PR they come back and I need to remove them again.

**Comment by Suor** [comment]
@ivyleavedtoadflax you selecting 12 columns in tracking scope doesn't mean anything else won't be parsed, this means that those 12 are guaranteed. If you simply want to hide some columns you can do it on a view page, this will happen immediately not requiring reimporting your repo or even refreshing the page. You can save that setting with a "Save changes" button in the top right part.

That said, tracking scope is not really a polished part of our UI and certainly far from intuitive. If you could describe your use case  and what are you trying to achieve with Studio that might help us improve it.

**Comment by ivyleavedtoadflax** [comment]
Thanks @Suor . Is it intended that I would need to reset the columns each time I make a PR?

I guess my use case is that:
1. I have a very large number of metrics
2. It's quite painful to try to select these in the columns tab in the view, especially if I need to do this each time I submit a PR.
3. I want to limit the columns that appear in the view either in the scope or in the columns (actually it doesn't matter which).

**Comment by Suor** [comment]
Tracking scope does not limit columns despite how it might look, it guarantees them. So trying using that for limiting won't really work.

> It's quite painful to try to select these in the columns tab in the view, especially if I need to do this each time I submit a PR.

Columns once hidden on a view page should not reappear given you saved changes. If they do then that is a bug. 

On that being painful I remember that we had filtering those in some of the designs. Did we decide to not implement this or is this still in works, @ssachkovskaya?

**Comment by ssachkovskaya** [comment]
> Columns once hidden on a view page should not reappear given you saved changes. If they do then that is a bug.

That's true. @ivyleavedtoadflax Could you please confirm that you clicked on the button "Save changes" once the columns visibility was set? Otherwise it is going to be reset next time you visit the page.

![image](https://user-images.githubusercontent.com/10098879/121502249-473d7780-c9e0-11eb-9f7f-dfd305046517.png)


@Suor Filtering the columns on the view page will be implemented, it is still in development.

**Comment by ivyleavedtoadflax** [comment]
Thanks @ssachkovskaya you're right, I think I was failing to save the view after making changes. I guess the feedback from this is that it was not 100% clear that I needed to click save to preserve the changes (actually, I'm not sure I noticed the save button at all).

**Comment by ivyleavedtoadflax** [comment]
> Tracking scope does not limit columns despite how it might look, it guarantees them. So trying using that for limiting won't really work.
> 
> > It's quite painful to try to select these in the columns tab in the view, especially if I need to do this each time I submit a PR.
> 
> Columns once hidden on a view page should not reappear given you saved changes. If they do then that is a bug.
> 
> On that being painful I remember that we had filtering those in some of the designs. Did we decide to not implement this or is this still in works, @ssachkovskaya?

Got it, thanks. Being able to filter columns like you filter scopes would be super helpful.

**Comment by ssachkovskaya** [comment]
> I guess the feedback from this is that it was not 100% clear that I needed to click save to preserve the changes (actually, I'm not sure I noticed the save button at all).

Yeah, you are right that it's not clear enough. We are already discussing how to improve this.
Thanks for your feedback!

**Comment by Suor** [comment]
Closing this as a support ticket since "save changes" are now more visible. Tracking scope being confusing will be handled separately.
