### ISSUE TITLE
Invalid SSL certificate error

### ISSUE THREAD

**Issue by liameabbott** [iterative/studio-support#100]
When trying to navigate to `https://studio.iterative.ai`, I get an `Invalid SSL certificate` error:

![Image](https://github.com/user-attachments/assets/bb35f6c6-8723-476a-985c-d1c627e669bf)

**Comment by shcheklein** [comment]
@liameabbott thanks! we are looking into this

**Comment by 0x2b3bfa0** [comment]
@liameabbott, resolved; apologies for the inconvenience!

**Comment by liameabbott** [comment]
Awesome, thank you!
