### ISSUE TITLE
Plots `Template ".dvc/plots/calibration" is not found in HEAD`

### ISSUE THREAD

**Issue by duijf** [iterative/studio-support#11]
A user reported a problem with plots not being able to load a custom template of theirs. Have taken a preliminary look, but couldn't figure out a cause immediately. Will continue investigating tomorrow.

Meta:

 - The user contacted us via Papercups.
 - Sentry link: https://sentry.io/organizations/iterative/issues/2449979663/?project=5175210

**Comment by duijf** [comment]
I have managed to reproduce this one. The user has a `dvc.yaml` with a config like this:

```yaml
plots:
  - some-plot.csv:
      template: ".dvc/plots/custom.json"
```

When Studio parses templates from the repository, we loop over files in `.dvc/plots` and store the plot data as `custom.json` instead of `.dvc/plots/custom.json`. That also means that we don't currently support plots stored in directories other than `.dvc/plots`, while DVC does work with those.

As a workaround the user can remove the `.dvc/plots` prefix from the template config in `dvc.yaml`.

We should also fix our plots code in Studio to (one of or both):

 - Strip the `.dvc/plots` prefix from custom templates if we see it.
 - Support custom templates in all directories like DVC does. This will require a careful implementation since there are security implications to using user input to read file contents.

Thoughts @Suor?

**Comment by Suor** [comment]
Should first confirm that this should work in DVC at all. Docs are saying nothing about that.

**Comment by duijf** [comment]
Filed https://github.com/iterative/dvc/issues/6179 with DVC

**Comment by Suor** [comment]
The fix was deployed a week ago, closing.
