### ISSUE TITLE
Self-hosted (custom domain) GitLab support

### ISSUE THREAD

**Issue by arjvik** [iterative/studio-support#12]
Studio already supports Gitlab.com, but it would be very helpful if it supported publically-accessible but self-hosted Gitlab instances as well!

**Comment by Suor** [comment]
Should be noted probably that on-prem installation of DVC Studio already works with self-hosted Gitlab.

**Comment by shcheklein** [comment]
For the record. @janchk Studio SaaS (studio.iterative.ai) doesn't work with self-hosted GitLab instances yet.

**Comment by janchk** [comment]
@shcheklein My bad. Got confused.

**Comment by tapadipti** [comment]
Now, Studio supports self-managed GitLab servers. Here's the doc on how you can set this up for your team: [Custom GitLab Server Connection](https://dvc.org/doc/studio/user-guide/connect-custom-gitlab-server)

A quick demo of how to set this up:
![custom_gitlab_gif_new](https://user-images.githubusercontent.com/32855442/164228937-f443080c-115a-482e-a579-22abf6ea4a40.gif)


You can also sign up with your email address, and then connect directly to your self-managed GitLab account (if you do not have or do not want to use your GitHub.com, GitLab.com or Bitbucket.org user accounts).

<img width="1140" alt="email_signup_with_arrow" src="https://user-images.githubusercontent.com/32855442/164228889-89a0c6ba-0fd6-4b50-b8f5-edf374559e77.png">
