### ISSUE TITLE
Add `live` metrics support

### ISSUE THREAD

**Issue by daavoo** [iterative/studio-support#13]
When working on some deep learning problems, it's common to have experiments running for hours (or even days). Some alternatives to `Studio` (i.e. wandb or mlflow) have some sort of "view" for individual experiments that is being updated as the training goes on. 

Within the "iterative ecosystem" there is the possibility of using [`dvclive` with `DVC`](https://dvc.org/doc/dvclive/dvclive-with-dvc) in order to "see a plot for metrics logged during the model training". 

I think it would be a good feature to have something similar (or even that same .html) integrated inside `Studio`.

**Comment by daavoo** [comment]
Without knowing details about the how `Studio` is implemented, this might be related to https://github.com/iterative/dvclive/issues/90 or even https://github.com/iterative/dvclive/issues/91, given that as far as I know `Studio` already detects CML comments

**Comment by Hommus** [comment]
I would very much appreciate this feature!

**Comment by casperdcl** [comment]
Related/might be solved by https://github.com/iterative/dvclive/pull/215

**Comment by daavoo** [comment]
Happy to close this one as completed 😄 

https://dvc.org/doc/studio/user-guide/projects-and-experiments/live-metrics-and-plots

**Comment by shcheklein** [comment]
Thanks @daavoo @dberenbaum @mvshmakov @nimdraugsael and everyone else who made this happen! 🎉
