### ISSUE TITLE
Authentication to Azure Blob Storage via None failed

### ISSUE THREAD

**Issue by aguschin** [iterative/studio-support#14]
After force import of this repo https://github.com/iterative/yolov5 I can see the error on that authentication to azure blob storage wasn't successful.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6797716/122226460-aeff3100-cebe-11eb-8c5d-458bd9c0b481.png">

But then it seems like Studio don't recognise this is necessary (no hint in settings), and when I add the credentials manually, the same error is show again after Force Import.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6797716/122226386-9a229d80-cebe-11eb-9e46-fcf077dc8c21.png">

Checked this in dev environment too.

**Comment by duijf** [comment]
Looks like this one is related to an internal PR: https://github.com/iterative/viewer/pull/2186

CC @Suor

**Comment by Suor** [comment]
The error is not properly recognized as missing or bad credentials one, I am working on that now. However, setting connection string should work. As far as I see none of your views are linked to any credentials so far.

**Comment by Suor** [comment]
Looks like it works on dev after using that connection string. BTW, you don't need to forcefully reimport on credentials change, a new import will be done for you automatically. Maybe you didn't click "Save changes" after selecting credentials? This is far from intuitive now that View settings page have grown and the "Save changes" button may be out screen. @arcticbear

**Comment by aguschin** [comment]
@Suor 
The credentials are saved. It’s interesting that the error disappeared, but after Force Import it is there again.

**Comment by aguschin** [comment]
> The error is not properly recognized as missing or bad credentials one, I am working on that now. However, setting connection string should work. As far as I see none of your views are linked to any credentials so far.

@Suor, can this be because I keep credentials in .env file which is not committed to repo? I think those credentials aren’t mentioned anywhere except that file. That credential necessity could only be implied by seeing “azure” in .dvc/config

**Comment by aguschin** [comment]
@Suor, it seem to work on dev environment now. Thanks!
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6797716/122569347-5319e100-d053-11eb-9d39-9e5d7342bd79.png">

**Comment by Suor** [comment]
Fix released.
