### ISSUE TITLE
Nested branches in DVC Studio GUI

### ISSUE THREAD

**Issue by janchk** [iterative/studio-support#17]
The bug occurs when DVC Studio tries to show branch that has no unique commits that differ form branch that current branch was created from.
Let me give you an example:

![Example](https://i.ibb.co/B48FTs7/git-dvc.png)

So, looks like "Some branch" is nested in Master and all commits of "Some branch" belongs to master. And DVC Studio shows it that way. 
But this isn't correct. "Some branch" is a separate branch in terms of git understanding, but DVC Studio thinks about it as a commit of Master. Therefore search and Filter features of DVC Studio isn't operate correctly because they can't operate with branch that recognized as a commit.

![GUI Example](https://media.discordapp.net/attachments/841856466897469441/855223736734842890/unknown.png)
Image above displays what I'm talking about.

**Comment by Suor** [comment]
Studio intentionally flats it up to make it more easier to display. The effect on filter and search is unintentional though. We'll take a look into it.

**Comment by mvshmakov** [comment]
@janchk thanks for the report!

Could you please elaborate on what explicitly do you mean by `search and Filter features of DVC Studio isn't operate correctly`. Would be great if you can share specific examples with your expectations.

**Comment by Suor** [comment]
@mvshmakov as I understand it on the picture above the red commit will be a part of master branch but also will have 'some branch' name so filter should work. However, if the red branch would have had more than 1 commit all of them aside from the tip won't be recognized as part of 'some branch' and filter by branch or search won't show them.

So this is not FE only problem we need to adjust how we collect and mark commits a bit as long as separate tag names from branches names.

So the question is the priority of this thing @shcheklein. I see this one as desirable though.

**Comment by janchk** [comment]
@mvshmakov 
For example in my repository I have "feature/ST-231-Epic" branch, which is nested or "flatted" and gitlab search works fine.
![2021-06-24_10-39](https://user-images.githubusercontent.com/9109987/123222821-001fae00-d4d9-11eb-9d10-ec952625ff64.png)
But I can't find the same branch in dvc studio interface. Because it does not recognized as one I suppose.
![2021-06-24_10-40](https://user-images.githubusercontent.com/9109987/123223403-89cf7b80-d4d9-11eb-8080-838a4b6e46ad.png)

**Comment by shcheklein** [comment]
> So the question is the priority of this thing @shcheklein. I see this one as desirable though.

Yep, let's address it. I've set as p1.

**Comment by Suor** [comment]
Researched this a little. And looks like this is not obvious conceptually.

Gitlab searches by branches but we search by commits. Technically starting commits belong to all branches making filtering by branch less useful. If we exclude starting commits then we have a question where is the branch start. Starting from master, i.e. default branch will work for most cases, but not for master + develop + features scenario. Starting from nearest junction might be ok.

**Comment by Suor** [comment]
Now merged branches should be found via filter and search. However, all the long common start of every branch is not included, i.e. if you look for branch `feature-1` branched out of master only the commits after initial branching out will be shown.

**Comment by Suor** [comment]
**NOTE.** Things should work automatically for all newer repos. Older ones need to be reimported with `Force import` action in their views 3 dots menu.

**Comment by jellebouwman** [comment]
Hi @janchk - just wanted to update you with a slight redesign of the branch filtering features in Studio. We found that it was more straightforward to split the filtering logic into two parts:

- Filter on branch names of branches that are shown in Studio -  `Branch` filter (original behaviour of the `Branch` filter)
- Filter on commits that are found on branches - `Commits on branch` filter (the filtering behaviour that we implemented when working on this support issue)

This split should offer users a bit more granularity in the way they filter. If you'd like to accomplish the filtering behaviour that you described in your original post, you'll have to switch to using the `Commits on branch` filter, which you can find as an option today:

<img width="921" alt="Screenshot 2022-09-21 at 10 20 26" src="https://user-images.githubusercontent.com/32744870/191375818-8beb75a5-b549-4960-b500-29a954c8731a.png">
