### ISSUE TITLE
Add option to hide unrelated commits

### ISSUE THREAD

**Issue by aguschin** [iterative/studio-support#18]
Currently we show all commits in Studio regardless of the changes in anything we track (parameters, metrics, outputs), but it is a common case when there are a lot of commits which aren't related to any changes in ML stuff. To name a few: changes in CI workflow files, changing documentation, editing configuration files which aren't related to ML model (.gitignore for example), etc, etc.

It may be the case that having more clean commit history showing only the commits which introduce changes will be more convenient for the user. As we already have "Delta mode" this is not very important, but I suppose there could be situations in which such option would be convenient.

related to https://github.com/iterative/studio-support/issues/15

**Comment by Suor** [comment]
This was actually present in the initial design. Was deferred for simplicity's sake, we may want to return to this now. Not sure though whether an extra line for a group of hidden commits as we had is the best solution. Maybe some more nuanced design with a hint between the lines and something showing on hover would fit better.

**Comment by mvshmakov** [comment]
We may also have a `toggle unrelated commits` kind of option in the view table header as we do with the `delta`, for instance. Anyway, would be great to have a design input here CC @arcticbear

**Comment by aguschin** [comment]
We've been discussing something very similar with @arcticbear on the last week. I've summarised the idea in the Notion https://www.notion.so/iterative/Ways-to-view-commits-in-Studio-00f81de787bf4d5b92b756faa87d2e5f
This is more about "what we'll do when we'll have ml models tracked with dvc", but this could be a right direction for us and this particular issue could be solved in more general context.
Feel free to check this out and provide your feedback, @mvshmakov @Suor @shcheklein

**Comment by tapadipti** [comment]
Studio now auto-hides commits that don't change metrics, hyperparameters or datasets (basically, the ML stuff). Users can also manually hide specific commits that they don't want to keep in the view. @aguschin what else would you like to address here?

**Comment by aguschin** [comment]
No, everything looks good! Thanks! Let's close the issue.
