### ISSUE TITLE
More detailed error report

### ISSUE THREAD

**Issue by daavoo** [iterative/studio-support#19]
When I click on `Show Warnings` I get a list of error messages saying `1 commit(s) failed to parse` but I don't know how to find which commit caused the error or how to get more details:

![Captura de pantalla de 2021-06-25 11-58-53](https://user-images.githubusercontent.com/12677733/123408275-1d25b100-d5ad-11eb-83f6-ef5369a1ea60.png)

I think it would be nice to have the option to see a more detailed error report.

**Comment by Suor** [comment]
If you open the view the error will be next to its commit. If commit is old then it might be hidden in "show more commits" though. There is no way to scroll to it or something like that, however if you don't see the errored commit line it shouldn't matter anyway.

**Comment by daavoo** [comment]
Thanks for the clarification @Suor , So in this case I should just ignore the warning, right?

**Comment by Suor** [comment]
Yes, you can hide it to not bother you.

Basically this means sometime ago you had a single commit where DVC things were broken somehow, e.g. a broken yaml. However if the broken commit is the last one then you'll probably want to fix that. You can see the same error message simply running `dvc status`.

**Comment by shcheklein** [comment]
Can we make it clear somehow? I guess other users will have the same question ... add link(s) to the commit?

**Comment by Suor** [comment]
How do you link to 22 commits? Do we even have links to commits at all? I can start collecting ids though as part of error and serve  it. 

Maybe we should simply improve the message instead. So that it will be clear that things mostly work and this is not critical.

**Comment by mvshmakov** [comment]
We have not yet implemented View commit links yet, but there is an issue with it - https://github.com/iterative/viewer/issues/1525. Linking to several commits is in the scope, but the original idea was to allow selecting only the subset of subsequent commits, while here we may end up with several broken commits across several different branches and the user might not be even interested in fixing all of the issues as stated by Alex.

I support improving the message and maybe extracting potentially interesting to fix ones. Is it possible to do it cheaply, @Suor? If not, we can just expand the documentation and link to it, so it would be at least a way to make it more clear to the users.

**Comment by shcheklein** [comment]
> So that it will be clear that things mostly work and this is not critical.

But it's hard to tell is it critical or not, right? Otherwise it seems that it's better to hide it completely.

**Comment by Suor** [comment]
I would say it is still useful to see. And it might be important if it's in HEAD or in a tip of some recent branch.
