### ISSUE TITLE
Error while accessing gitlab view

### ISSUE THREAD

**Issue by janchk** [iterative/studio-support#20]
When I try to open gitlab view the following error is prompted:

**Something went wrong**
c[p] is undefined
![smth_wrong](https://user-images.githubusercontent.com/9109987/124011541-ca9f2700-d9e8-11eb-8668-73dda719d9bd.png)

## Expected Behavior
The view have to be displayed.

## Current Behavior
Error instead of a view.

## Steps to reproduce
1. Connect a Gitlab account to Studio
2. Create group in Gitlab
3. Add project in this group
4. Try to import this project into DVC Studio

## Workaround 
Import only personal projects.

**Comment by shcheklein** [comment]
Hey, @janchk ! Thanks for the report, we'll be looking into this as soon as possible.

**Comment by mvshmakov** [comment]
Hello, @janchk, thanks for the bug report!

Are you experiencing the same error at the same Bitbucket-imported repo?

**Comment by janchk** [comment]
@mvshmakov No. Even gitlab-hosted projects works fine. Except that they are not group related. To be more exact I had project on gitlab that belongs to user, that works fine with DVC.  Then I transferred that exact project to the gitlab group, imported it again, removed the older one and presented problem had happened.

Hope that helps.

**Comment by Suor** [comment]
Looked into it. It's either FE bug or BE sends something FE doesn't expect. Can you take a look @mvshmakov?

**Comment by jellebouwman** [comment]
@janchk we have functionality in place to impersonate your user account in the Studio application. We need to use this feature to get to the bottom of this issue - would you be okay with us using this?

**Comment by janchk** [comment]
@jellebouwman No. I would be NOT okay with this. The project I'm working on is not completely mine. I can answer to any question though. Here or on discord.

**Comment by mvshmakov** [comment]
@janchk We'll not use this functionality then, thanks for letting us know. We'd do our best to improve our error reporting tools that are not exposing the user's data to any of the staff people.

For now, may I ask you to disable the `uBlock origin` and/or any other adblocking extensions you have in the browser and try to trigger this error again (visit this failed View page)? We'll not receive any of your sensitive project-related information and will not show any ads, we'll just receive the place where the error happened in our code and what has triggered it, so we can investigate and fix it to improve your Studio experience.

**Comment by janchk** [comment]
@mvshmakov Done.

**Comment by mvshmakov** [comment]
The error is resolved as to what @janchk has reported. It was done by making the app more tolerant to the parsed data and by improving error reporting logic, but the source of the problem still present in the app. Filed a new issue for more in-depth research https://github.com/iterative/studio-support/issues/25
