### ISSUE TITLE
Add a view encounter network error

### ISSUE THREAD

**Issue by haroldyangui** [iterative/studio-support#24]
After I install the github app and grant permissions to repos, when I add a view, encounter unexpected network error.
The repository is under my working company organization, but I have the permission of admin for those repos, and can see the installed applications.

Trace id xRL1QW2ZG-Fkpu-PtkhLe

![image](https://user-images.githubusercontent.com/57379766/125394609-83e40080-e3dc-11eb-8ca1-1d5a4352f52f.png)

**Comment by Suor** [comment]
@haroldyangui Github does not permit listing repositories for your DVC Studio installation, is it possible that installation is suspended or in some other weird state? You may try fixing this by going to your profile in DVC Studio and clicking configure button next to Github App [here](https://studio.iterative.ai/user/_/profile?section=gitIntegrations). You'll be redirected to a page on Github with DVC Studio Github App settings. You might need to unsuspend it or review or select accessible repos, if all that fails you can simply uninstall DVC Studio from your Github account and then install it again.

We don't handle this error properly now thus this unhelpful message, I'll look into that.

**Comment by Suor** [comment]
@haroldyangui I also see that you have installed DVC Studio both into your personal and into an organization account. So need to check both. Not sure link above will guide you to both places (how does it work @duijf?), but it should be:

https://github.com/settings/installations and https://github.com/organizations/ORGANIZATION-NAME/settings/installations (Organization page -> Settings -> Installed Github Apps)

**Comment by duijf** [comment]
@haroldyangui We are receiving this error message from GitHub:

```json
{
    "message": "Although you appear to have the correct authorization credentials, the `[redacted]` organization has an IP allow list enabled, and x.x.x.x is not permitted to access this resource.",
    "documentation_url":"https://docs.github.com/rest/reference/apps#list-repositories-accessible-to-the-user-access-token"
}
```

So it appears that your organization has IP whitelisting configured on GitHub which means that we are not able to fetch the repositories list from Studio. I wasn't aware this was possible, but it seems like this is [a feature](https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-allowed-ip-addresses-for-your-organization) of GitHub Enterprise Cloud.

 - We don't handle this case gracefully and need to improve the error (and still show the repositories of the accounts / GH app installations that we did manage to fetch).
 - We don't currently publish a list of all the IP addresses that we use to fetch data from SCM providers (we need to discuss if we can commit to publishing this list + making sure it's updated  / doesn't change a lot)

**Comment by Suor** [comment]
@duijf do you want to take this issue?

**Comment by duijf** [comment]
Like I posted before, we don't have great error handling capabilities on this page yet. I will proceed with a quick fix to unbreak the create view page for you @haroldyangui so you'll be able to create views for repos outside of this specific GitHub org.

**Comment by duijf** [comment]
@haroldyangui A fix to unbreak the "Create view" page for you is scheduled for tomorrow. After the fix, you will still be unable to see the repositories from the org with the IP whitelist, but at least you will be able to add new views for your other repos.

**Comment by duijf** [comment]
@haroldyangui The "Create View" page should be unbroken for you now, but you will still not be able to view / add repositories for this specific organization until:

 - The organization removes the IP whitelisting requirement.
 - We publish a list of our IP addresses for the organization to include in their whitelisting policy.

Hopefully this gives you the chance to try out Studio and see whether you like it :)

Some follow up for us:

 - Currently we just hide the specific organization if we fail to fetch it's data, but don't actually tell you why we cannot fetch certain GitHub organizations. There is an internal ticket to improve this and I will post a follow-up here once it has been implemented.
 - We need to consider whether we're willing to publish a stable range of IP addresses that we use to import stuff from GitHub. I've filed https://github.com/iterative/studio-support/issues/26 to track this.

For now, I will close this one as the most urgent part has been solved (and we have tickets for further improvement).

@haroldyangui Please feel free to re-open this issue if you feel like something is still left unaddressed :smile:

**Comment by shcheklein** [comment]
@duijf thank you for addressing this?

> but don't actually tell you why we cannot fetch certain GitHub organizations.

how hard would it be to show that something is wrong with the connection (in the settings page?).

**Comment by duijf** [comment]
> how hard would it be to show that something is wrong with the connection (in the settings page?).

@shcheklein FYI I created this (internal) ticket to show it on the "Create new view" page: https://github.com/iterative/viewer/issues/2317

Having this on the settings page in addition means making external requests when the settings page is loaded or saving the results of the DB + having some sort of refresh mechanism. Both are possible, but it requires some work.

I would start with adding this to the "create new view" page on load, since we're making those external requests there already. We probably want some reporting on that page anyway, since the external requests we're making can fail for other reasons as well. (E.g. GitHub downtime currently means some repos would not be shown, also without a notice to the user).
