### ISSUE TITLE
Dangling experiment persists in the view even after the force parsing

### ISSUE THREAD

**Issue by mvshmakov** [iterative/studio-support#25]
Related https://github.com/iterative/studio-support/issues/20.

After the initial problem, the user has experienced the dangling branch with an experiment that is not even present in the repository. Force import is not helping the situation. It might be related to the GitLab runner logic handling after the experiment run, but it needs to be researched more.

![image](https://user-images.githubusercontent.com/28868855/125612696-4a7d10e8-1ea8-4e0f-b8ab-ce1def2b6c3e.png)

**Comment by shcheklein** [comment]
@mvshmakov @JIoJIaJIu is it done?

**Comment by janchk** [comment]
Have gotten away from internet for a time. Nope, problem still persists.
![2021-08-30_18-27](https://user-images.githubusercontent.com/9109987/131364851-fa1903ae-10b7-442d-87b9-a5537ee45744.png)
@shcheklein

**Comment by gurobokum** [comment]
Hello @janchk 
The fix was shipped to the production
Could please you provide the steps on how to reproduce the issue you have?

The dangling experiment commits should disappear on page refresh - could you prove it?
We are working yet on hiding it automatically without user actions

**Comment by janchk** [comment]
@JIoJIaJIu Yes. Problem was solved! I think issue can be closed.
