### ISSUE TITLE
Publish a list of our IP addresses

### ISSUE THREAD

**Issue by duijf** [iterative/studio-support#26]
In https://github.com/iterative/studio-support/issues/24 we discovered that GitHub Enterprise Cloud has an IP allow-list feature. Administrators of organizations can configure an allow list of IP addresses that can access resources in their organization.

We currently do not publish such a list of IP addresses. Publishing one and supporting it requires a commitment from Iterative + has operational challenges and costs.

This issue exists to gauge interest in publishing such a list. Please leave a :+1: or :heart: reaction in case you would like this.

**Comment by mvshmakov** [comment]
Great idea to collect the feedback, @duijf! Should we limit the "poll" by time following with the issue closing, and just wait for the reopen requests in case we don't find enough interest?

**Comment by duijf** [comment]
Proposal: Let's keep this open for ~90 days and see if there is any activity. We can close it if there isn't any and reopen if there is interest down the line.

If we don't want to leave things open for that long in this repo, maybe we could have another one for feature requests?

**Comment by mvshmakov** [comment]
@duijf proposal seems wise to me. Though I don't think we need to have another repo for feature requests, it would be very confusing :) 

What I suggest instead is to allow GitHub `discussions` feature in this repo for the feature requests that require a discussion/public opinion collection and reserve a `feature request` tag for issues in this repo for the features that are not too hard or uncertain to implement.

**Comment by duijf** [comment]
Small update: It seems like GitHub now allows GitHub apps to specify a list of their IP addresses. Don't know when they added this capability, but I hadn't noticed this setting before. This means we can attach a list of our IP addresses to our GitHub app and they will be automatically updated in all organizations with IP whitelisting enabled.

That provides a solution for the annoyance of requiring action from users in case we change our IP ranges. Docs about this are here: https://docs.github.com/en/developers/apps/building-github-apps/managing-allowed-ip-addresses-for-a-github-app

**Comment by shcheklein** [comment]
Closing this for now since there was not interest among users and customer so far.
