### ISSUE TITLE
Feature Request: make link to github repo open new tab

### ISSUE THREAD

**Issue by davesteps** [iterative/studio-support#27]
Would be nice if link to the associated repo opens up a new tab rather than losing your dvc studio page.

**Comment by ssachkovskaya** [comment]
Thanks for your request! Did you mean "View on GitHub" or another link?
![image](https://user-images.githubusercontent.com/10098879/126168959-cd25ca5b-8d1c-46f6-a983-7d15bd749ac6.png)

**Comment by davesteps** [comment]
Sorry, yes that is the link I'm referring too

**Comment by ssachkovskaya** [comment]
The fix is available in Studio now. @davesteps thanks again for reporting this and let us know if you find any other related issues!
