### ISSUE TITLE
Metric Changes/Comparison Sidebar Float Column Headers

### ISSUE THREAD

**Issue by mattangus** [iterative/studio-support#28]
Hi,

When using the comparison mode between two commits I've noticed when using a long list of metrics scrolling makes the column headers disapear. I have to keep scrolling up to remind myself which columns are for which commit. It would be nice to have them float over the data like in the main view showing commit histories.

**Comment by shcheklein** [comment]
Thanks @mattangus ! I love the idea and it makes sense and should be easy to implement!

**Comment by mattangus** [comment]
Awesome!

**Comment by ssachkovskaya** [comment]
We have improved the scrolling experience when comparing two commits.
@mattangus thanks for your request and let us know if you find any other issues!
