### ISSUE TITLE
View settings fails because of the custom configuration of chosen columns

### ISSUE THREAD

**Issue by mvshmakov** [iterative/studio-support#3]
The user can't open the view settings page after setting the custom set of chosen columns.

The issue was created from the Papercups support channel, intended to be closed after the fix is shipped.

**Comment by shcheklein** [comment]
@mvshmakov hey, do you know if it is fixed? Have we communicated back?

**Comment by mvshmakov** [comment]
That is fixed. @courentin sorry for the late response, but you may check out things in Studio, it should work properly now. Feel free to contact us about anything you have in mind ;)
