### ISSUE TITLE
Update view popup pushes bottom scrollbar off the screen

### ISSUE THREAD

**Issue by mattangus** [iterative/studio-support#30]
When a new commit is added, a popup shows up at the top of the page asking to refresh the view. This popup causes the bottom scrollbar to be pushed off the bottom  of the screen. This means that you first have to scroll down in order to scroll left or right on the metrics panel. This is in contrast to the "Review tracking scope" popup at the top that does not push the bar off the bottom. I think the desired behaviour is to have the view resize to accommodate the popup rather than requiring scrolling.

**Comment by jellebouwman** [comment]
Thank you for reaching out to us @mattangus, it's highly appreciated! 🙏 I've opened a PR fixing this bug, I'll report back here when it gets released to production!

**Comment by jellebouwman** [comment]
Thanks for reporting, this fix has been released to production!
