### ISSUE TITLE
Non-responsive Tracking Scope Settings

### ISSUE THREAD

**Issue by jdegregorio** [iterative/studio-support#32]
I have a private view that tracks a project with > 200 tracked metrics/params.  For obvious reasons, the table does not show all of these metrics/data/params in the table, but there appears to be a bug with updating the "Tracking Scope" settings in this situation. I have tried numerous times to adjust the settings to <10 values, or even clear out all tracking scope, but every time the view updates/re-imports after clicking save, it still comes back trying to display all of the possible values (> 200)  again and shows the warning to reduce scope.

**Comment by shcheklein** [comment]
I've increased the priority for this. @jdegregorio we'll try to review this asap.

**Comment by jdegregorio** [comment]
> Hi @jdegregorio , I assume you are talking about DVC Studio, right?

Yep, sorry I didn't specify.

**Comment by Suor** [comment]
This seems to me a dup of #10.

@jdegregorio are you trying to use Tracking scope to limit columns showed in a view? The thing is tracking scope is designed to guarantee you columns parsed, it doesn't mean anything not selected won't be parsed and shown. To hide columns you may simply hide/show them on the view page and then save changes (a button at the top) - this won't require reimport and thus is fast. Columns saved to be hidden this way won't reappear. 

You only need to go to tracking scope if the column you want is not in the view at all - didn't fit into our limit and weren't heuristically detected as a desired one. Once you have everything you want or at any moment for that matter you may dismiss tracking scope warning.

We understand this tracking scope/shown columns duality is confusing though and discussing on how to make it better. The internal ticket for that is https://github.com/iterative/viewer/issues/2243.

**Comment by mvshmakov** [comment]
@shcheklein in what way do we want to tackle this issue?

This is not really a p0 because it is not a bug, it is how things are intended to work. The question here is should we add it in the docs/improve messages in the Studio directly or repurpose the whole Tracking Scope idea? The last option has its own complications because it is not that easy to make it work as the users expect, the details are defined in the internal issue.

**Comment by tapadipti** [comment]
Hi @jdegregorio We are trying to determine the changes/fixes required to resolve this issue.  Some time back, we improved the messaging around `Tracking scope`, which is now called `Mandatory columns`. Could you please let us know if the Mandatory columns (aka, Tracking scope) settings are still confusing/buggy or whether you have been able to hide unnecessary metrics/params as desired?

**Comment by omesser** [comment]
No response here for a long time and given we have https://github.com/iterative/studio/issues/2243 to track rethinking the behavior, I think this should now be closed (cc @shcheklein @tapadipti or anyone else, please reopen if disagree)

**Comment by tapadipti** [comment]
I've added a reminder in https://github.com/iterative/studio/issues/2253 to inform the user once we close the related internal issues.
