### ISSUE TITLE
Add possibility to delete failed experiments in DVC Studio

### ISSUE THREAD

**Issue by janchk** [iterative/studio-support#35]
'Failed experiment' section is kinda annoying to be on the board all the time. Eventually amount of failed experiments is getting bigger.  It would be nice to have some 'delete' button to remove it.

**Comment by duijf** [comment]
Thanks for the request! Can see how this would get annoying, we should indeed have the option to delete them.

**Comment by jellebouwman** [comment]
@janchk - we've released a new version of Studio that allows you to specifically delete experiments that have failed. You should see a new icon next to the error notification that allows you to perform this action.

<img width="796" alt="Screenshot 2021-10-20 at 16 41 18" src="https://user-images.githubusercontent.com/32744870/138115207-98fdf6df-2fe3-41c0-84d4-1eda9ad87305.png">

--- 

Closing this - if you have any followup feel free to re-open. Again, thanks for your suggestion, we appreciate it a lot!
