### ISSUE TITLE
bug: can't save changes in 'review mandatory columns'

### ISSUE THREAD

**Issue by olivierr42** [iterative/studio-support#38]
Steps to reproduce:
1. Open review mandatory columns tab
2. Add/remove columns
3. Click save changes 

Error 400: Request failed message shows up in red in the top right.

**Comment by mvshmakov** [comment]
@olivierr42 @AlexandreDuperre thanks for getting in touch and reporting the issue. It was fixed, so I'm closing this issue. If you encounter any other problems, please, create additional issues.
