### ISSUE TITLE
Feature request: allow to select "default" branch

### ISSUE THREAD

**Issue by aguschin** [iterative/studio-support#4]
If you have no .dvc in the master branch, Studio won't parse it, for example:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/6797716/120333418-56456b00-c2f8-11eb-9908-d02daad128f1.png">

Suggestion: add an option to select some branch to be "default", probably in the repo settings in Studio.

Motivation: This could be inconvenient if you already have a repo without dvc and now are trying out dvc in some other branch, to later create a PR. Of course, as a workaround, you could fork repo and add dvc in master branch,  but in this case you lose all CI/CD set up (runners, variables, etc) -- and if you want to use dvc in CI, you will need to deal with setting up CI/CD in your local repo which could be a waste of time. 

For me it's unclear how frequent this scenario is, but it's definitely exists. Feel free to add +1 and leave a comment if you need this functionality or suggest how to deal with this more gracefully.

**Comment by Suor** [comment]
Alternatively we can simply parse all branches having `.dvc` in display them. No user input needed.

**Comment by aguschin** [comment]
@Suor, sounds good! But doesn't Studio use some branch as baseline to show other branches against that one? Or this also could be decided automatically?

**Comment by Suor** [comment]
The HEAD - a tip of a default branch - is used as a baseline, but any other commit may set as one. Not sure we allow no baseline at all, but we may simply choose the longest branch and its tip if we need to. The same for history flattening.

**Comment by Suor** [comment]
Implemented support for `.dvc` in a non-default branch. The things will show as usual, branches without `.dvc` will simply have no metrics nor files, might still have params from `params.yaml`, since that is a default place. For existing repos `Force import` will do.

Deploying now.
