### ISSUE TITLE
Only show true experiment commits & Declutter UI

### ISSUE THREAD

**Issue by karpatika92** [iterative/studio-support#42]
I was delighted by the new update that hid commits that do not change metrics compared to the default branch. 

Unfortunately, cosmetic commits and so on are still shown! I'd suggest showing commits that change metrics compared to the previous commit, instead of compared to the head of the default branch! This would declutter the UI a LOT. 

Another option would be to only show branch heads by default, and expand them on request. Right now only expanded branches have any metrics shown. 

Eg.: I often create a new feature, train a model to see if it works, then I need to change a bunch of stuff to make CI/CD & unit tests work.

**Comment by ssachkovskaya** [comment]
@karpatika92 thanks for reporting the issue! We have released some fixes to hide commits which have no metric or param changes compared to the previous commit. Can you please check and let us know if that's something you expect to see?

**Comment by ssachkovskaya** [comment]
Closing this issue as it must be resolved now. It can be reopened later if additional changes are required.
