### ISSUE TITLE
Unexpected Error When Running a new Experiment in Studio

### ISSUE THREAD

**Issue by TransMux** [iterative/studio-support#46]
I just made a commit to my github repository, and tried to **run a new Experiment** in Studio.

I have set up a `Github Action` which will run `CML workflow` in a `self-hosted` server. By Running a new Experiment in Studio, I expect that it will make a commit to my `github repository`, and trigger the Action to run the training process. But then i met the problem.
**The ScreenShot below describes my operations.**

![image](https://user-images.githubusercontent.com/88016816/151592859-834a9ae0-c660-4327-9af5-f668ee9f554c.png)

**I guess the problem occurs when commiting to github, because my github repository didn`t receive any update.**

Maybe i should set up a token somewhere to provide access to my private repository?

**Any suggestions are welcomed !**

**Comment by shcheklein** [comment]
Thanks @InEase for the report, we are looking into this.

**Comment by amritghimire** [comment]
@InEase The support for python param file is still experimental for dvc (See https://github.com/iterative/dvc/issues/5777). 
As a workaround for now, You can use the yaml/toml/json files or class based parameter as illustrated in [example python parameter file](https://dvc.org/doc/command-reference/params#examples-python-parameters-file)
Thanks.

**Comment by amritghimire** [comment]
We have introduced specific error message for the error above. Changing the priority of the issue since the support for python param file is still experimental.
