### ISSUE TITLE
Sort numerical parameters

### ISSUE THREAD

**Issue by daavoo** [iterative/studio-support#47]
When `Parameters` have numerical values, they are still recognized as a string. 

This causes the sorting result to don't match what I would expect:

<img width="1537" alt="Captura de pantalla 2022-02-09 a las 13 22 29" src="https://user-images.githubusercontent.com/12677733/153200367-59f12318-b9f8-477a-9272-d971598df318.png">

The capture comes from applying sorting to the `max_features` param in the Studio Demo Project:

https://studio.iterative.ai/team/Iterative/views/example-get-started-zde16i6c4g?sort=param%3Bparams.yaml%3Afeaturize.max_features%3BASC

**Comment by ssachkovskaya** [comment]
@daavoo Thanks for you report! The issue must be fixed now.
We just noticed that a menu option is still called `Sort A-Z` for numeric params which we will fix soon, but this is only a UI issue and you can already start using the correct numeric sort.

**Comment by daavoo** [comment]
Is the change deployed? The sorting doesn't appear to be working properly (from `example-get-started` demo):

<img width="925" alt="Captura de Pantalla 2022-05-06 a las 22 03 38" src="https://user-images.githubusercontent.com/12677733/167209366-12f9845d-83e6-4692-94d2-dbf65e4b2dd9.png">

**Comment by jellebouwman** [comment]
@daavoo the change is deployed - you are probably looking at an older parsed view where these param values are still served to the front-end as strings. Forcing a re-import should enable you to sort these params as numbers - ran into the same issue and it worked for me. 👍
