### ISSUE TITLE
Can't integrate with my github repos and "Configure" link not working

### ISSUE THREAD

**Issue by RR-28023** [iterative/studio-support#48]
Hi,
I can't currently see any of my repos. And then if I click on `Configure Git integration settings` (see below)
![image](https://user-images.githubusercontent.com/36822895/158568109-b0724ab9-e534-44b3-9c34-ff48dc02cde7.png)

I'm directed to this page, but then when I click on the `Configure` button. The link returns a 404 response.

![image](https://user-images.githubusercontent.com/36822895/158567913-232b6f6b-127b-4252-a9f8-1334aa74591f.png)

![image](https://user-images.githubusercontent.com/36822895/158568586-f827f20c-83d6-42b3-be21-2ebe4efa3dd2.png)

Any idea on what's the issue / why the link does not work?  (I have granted Iterative Studio access to my github account) 
Thank you.

**Comment by mvshmakov** [comment]
Hey, @RR-28023, thanks for the report!

We recently changed the name of our GitHub App from `DVC Studio` to `Iterative Studio` and this link was not updated, unfortunately. To configure the GitHub App, please, use the following link: https://github.com/apps/iterative-studio/installations/new.

We'll make sure to update the link in the Studio ASAP.

**Comment by mvshmakov** [comment]
We have fixed the issue. Feel free to open a new issue if the problem persist!
