### ISSUE TITLE
React rendering error

### ISSUE THREAD

**Issue by jellebouwman** [iterative/studio-support#49]
After a recent release, a React error is being thrown on certain views:
https://reactjs.org/docs/error-decoder.html/?invariant=31&args%5B%5D=object%20with%20keys%20%7Bdir%2C%20target%2C%20feature_names%7D - indicating we're incorrectly processing some data.

**Comment by jellebouwman** [comment]
Currently investigating the cause of this issue.

**Comment by jellebouwman** [comment]
Able to reproduce the issue, looking into a fix.

**Comment by jellebouwman** [comment]
Found the location of the bug, testing the fix 👍

**Comment by jellebouwman** [comment]
A hotfix has been made, we'll hopefully release a new version of Studio today that fixes this issue.

**Comment by mvshmakov** [comment]
The release containing the fix is deployed.
