### ISSUE TITLE
Not all repositories are showen using Gitlab

### ISSUE THREAD

**Issue by aadeg** [iterative/studio-support#5]
In the `Add a view` page I can't find some of the repositories that I have on Gitlab. I tried to search the missing repositories using the search bar at the top of the page, but I didn't find any of them.
I'm the owner of the missing Gitlab repository so I don't think is a permission issue.

## Expected Behavior
In the `Add a view` page all the repositories from Gitlab have to be displayed.

## Current Behavior
Only few repositories from Gitlab are showen in the `Add a view` page

## Step to reproduce
1. Connect a Gitlab account to Studio 
2. Click on the upper right button `Add a view`

## Possibile solution
In my Gitlab account I've access to a lot of projects. Maybe the issue is caused by a limit in the Gitlab API: I saw on the Gitlab API documentation that the API uses a pagination system (https://docs.gitlab.com/ee/api/#pagination).

**Comment by Suor** [comment]
Thanks for getting in touch. I looked at the code and it's possible pagination is the culprit. How many repos do you have there?

**Comment by aadeg** [comment]
I don't have an exact number, but about 100.

**Comment by Suor** [comment]
Anyway, we'll look into it.

**Comment by Suor** [comment]
Fix released. @aadeg do you see all your repos now?

**Comment by aadeg** [comment]
Fixed. Thanks :+1:
