### ISSUE TITLE
Having different names for multiple views created out of the same repository

### ISSUE THREAD

**Issue by SathvikNapa** [iterative/studio-support#51]
Currently, while I create multiple views for the same repository, I am seeing the same name for them.
The use case where different names might be beneficial is when I need to share my experiments with different stakeholders across the board:
1. Peers looking through the experiments and contributing to the project.
2. Managers looking through the metrics and a selected list of experiments that I can slice and dice for them.

**Comment by tapadipti** [comment]
Hi @SathvikNapa You can rename your views after creating them. Open the view settings, and in the first section (`View name`), you can provide a new name for your view and then save the change. Does this resolve your issue?
