### ISSUE TITLE
Bug(?): Hide toggle says commits are hidden even when they are not

### ISSUE THREAD

**Issue by dberenbaum** [iterative/studio-support#52]
Even when the toggle is set to show hidden commits, the tooltip says commits are hidden, unless I'm misunderstanding. Could it instead toggle to say something like "(6 will be hidden)" when the hidden commits are visible?

<img width="1440" alt="Screen Shot 2022-06-09 at 11 39 08 AM" src="https://user-images.githubusercontent.com/2308172/172888070-f19b352a-57db-426f-b22f-a989657c415f.png">

**Comment by jellebouwman** [comment]
@dberenbaum thanks - that makes sense! I'll get a quick PR out to address this.

**Comment by jellebouwman** [comment]
Released on production, closing this ticket.
