### ISSUE TITLE
Plots: an error has occurred: Field 'Metric' does not exist in provided data

### ISSUE THREAD

**Issue by shcheklein** [iterative/studio-support#6]
> I'm having an issue with plots, when I click on "Show plots" I got a "An error has occurred: Field 'Metric' does not exist in provided data." error.
Is it something I should fix on my end or is it a known issue?

**Comment by Suor** [comment]
This is an error within a repo, i.e. a csv-file doesn't have `Metric` column. Command line DVC will show the same error on `dvc plots show rev1 rev2 rev_affected`. Since we reuse the same code in Studio we can't constrain the error to a particular plot nor to a  revision, at least without significant focus on plots in Studio.

**Comment by shcheklein** [comment]
@Suor can we detect which plot (commit) is broken and ignore it?

**Comment by Suor** [comment]
It might and probably will require changes to DVC code too and then corresponding changes in Studio, so not a quick fix. Everything is possible of cause)

**Comment by shcheklein** [comment]
@Suor lets initiate this process on the DVC end. We need at least know which one is broken so that we can show that one. 

Another idea - while we are parsing commits - could we run some "health" checks on our end to detect this?

**Comment by Suor** [comment]
> Another idea - while we are parsing commits - could we run some "health" checks on our end to detect this?

We can. It might be expensive though. Also, will require Studio know they more about DVC plots internals or DVC exposing some more stuff or both.

As I said properly handling this will require significant focus on plots.

**Comment by shcheklein** [comment]
@Suor please confirm - it should be partially solved? @Benjamin-Etheredge I think you had this problem, could you please check that it works now for you?

**Comment by Suor** [comment]
Yes, the fix was shipped. We show whatever we can show now. We won't show this error though.
