### ISSUE TITLE
Could not connet github 

### ISSUE THREAD

**Issue by mehadi92** [iterative/studio-support#60]
When I click on "connect GitHub" I get an account already in used
![Screenshot from 2022-09-27 11-52-09](https://user-images.githubusercontent.com/104126711/192443819-03d0f9bc-17ec-41d2-bde8-55c5d587471e.png)

**Comment by mvshmakov** [comment]
Hey, @mehadi92, thanks for the report!

This message means you've already used your GitHub account to log into another Studio account. We don't support connecting a single GitHub account to several Studio accounts. In addition, we currently don't have a "merge accounts" option.

So, to help us solve your issue, could you please answer the following questions:
1. How have you entered the current account? Was it by using an email login or other social logins (GitLab/Bitbucket)?
2. Do you have any projects created on the previous account? Do you have any projects created on the current account?

**Comment by mehadi92** [comment]
Hi @mvshmakov,

1st I try to login with GitHub social account, But during login, I miss type my email address so I could not verify the email
2nd I try the login email option, where I give the necessary information and login with my correct email add, and was able to verify this email. From this login when I try to connect the Github I'm getting "An account already in used" 

I don't create any project in my previous account or current account

**Comment by mehadi92** [comment]
@mvshmakov , 

My approach to login in using a social site (GitHub) fails as follows. As you can see I highlighted the wrong email address. I think if I could delete my social login then the problem can be solved. But I can't find any option to delete social login 

![Peek 2022-09-27 14-55](https://user-images.githubusercontent.com/104126711/192481311-69ad3950-d00b-4a54-9534-8c560446db6a.gif)

**Comment by mvshmakov** [comment]
@mehadi92 hey!
Could you please try to connect the GitHub once again? We've removed all of your accounts except the Gmail one which should help you.

**Comment by mehadi92** [comment]
Hi, @mvshmakov, I could not log in with my Gmail and the corresponding password. I also try to recover the password option. it also doesn't send me any recovery link. Do I need to signup again with my email?

**Comment by mvshmakov** [comment]
Hey @mehadi92!

I've tried to reach you in Discord but received no response. What is the best way for us to reach you directly and help?

**Comment by mehadi92** [comment]
@mvshmakov I can log in to the iterative studio after re-creating a new account with my email - Thanks.
The best way to reach me is my email `mehadihasan80@gmail.com`
