### ISSUE TITLE
Top-level plots images fail

### ISSUE THREAD

**Issue by dberenbaum** [iterative/studio-support#63]
See https://studio.iterative.ai/user/dberenbaum/projects/example-get-started-67p6ussc8t?panels=plots%2C&commits=5709915%2Cprimary.

<img width="1436" alt="Screenshot 2022-11-28 at 9 20 15 AM" src="https://user-images.githubusercontent.com/2308172/204301174-063dce35-9179-481e-bf59-0ce3fe1848ea.png">

I have checked that the file exists on the remote, which is publicly accessible. Other branches that don't use top-level plots section can successfully render the image.

**Comment by ssachkovskaya** [comment]
@iterative/studio-backend can you please have a look why it cannot be parsed?

**Comment by amritghimire** [comment]
@ssachkovskaya 

  The error here seems to occur when there is no data for the datasource . Reference: [L225-L231](https://github.com/iterative/studio/blob/fbc4362c58449b33d28773bfe4855081d141821b/backend/repos/parsing/dvcmeat.py#L225-L231) . 

We are basically inferring the data source from the dvc and load plot data in studio as in [L180-L183](https://github.com/iterative/studio/blob/fbc4362c58449b33d28773bfe4855081d141821b/backend/repos/parsing/dvcmeat.py#L180-L183)

@dberenbaum Can you see if we have proper response from dvc to load the data here?

**Comment by dberenbaum** [comment]
`dvc plots show` has no problem getting the data from the remote in CLI.

**Comment by shcheklein** [comment]
@dberenbaum project is not accessible anymore, could you reproduce and refresh the link and share the link to GH please?

**Comment by dberenbaum** [comment]
Sorry, project was private. Made it public now. Here's an updated link: https://studio.iterative.ai/user/dberenbaum/projects/example-get-started-67p6ussc8t?panels=plots%2C&commits=5710037%2Cprimary

**Comment by amritghimire** [comment]
The issue has been fixed and released.
