### ISSUE TITLE
Top-level confusion matrices failing

### ISSUE THREAD

**Issue by dberenbaum** [iterative/studio-support#64]
Related to #63 (and maybe to https://github.com/iterative/vscode-dvc/issues/2516).

In https://studio.iterative.ai/user/dberenbaum/projects/example-get-started-67p6ussc8t?panels=plots%2C&commits=5710037%2Cprimary, there should be two confusion matrices shown. Here's the output in `dvc plots show`:

![visualization(12)](https://user-images.githubusercontent.com/2308172/204576114-80bda518-9c13-4a49-a586-10c0d6a086fc.png)

In Studio, I only see one confusion matrix that combines the data from both data sources.

**Comment by jellebouwman** [comment]
Addressed

**Comment by jellebouwman** [comment]
We just merged a fix for this, I'll close this issue when we release this on production. cc @dberenbaum
