### ISSUE TITLE
Legend broken for multi-source plots

### ISSUE THREAD

**Issue by dberenbaum** [iterative/studio-support#66]
The circles in the legend look identical -- I think they are supposed to show different stroke dash values (it's a bit hard to tell due to other issues with the plot unrelated to Studio)?

![visualization(23)](https://user-images.githubusercontent.com/2308172/214693366-fdd12052-c904-4f21-813f-932406676067.png)

**Comment by shcheklein** [comment]
Closing in favor of an internal one. We'll be working on this soon.
