### ISSUE TITLE
Can't open help chat

### ISSUE THREAD

**Issue by haimat** [iterative/studio-support#70]
I wanted to get help via chat using the "Chat" option in the dropdown menu of my user.
However, the popup remains white and empty:

![image](https://user-images.githubusercontent.com/6633976/219376147-f3b5dec2-3e2d-455c-99dc-214ea077199e.png)

I am using Firefox, if that is important, its developer console gives this:

> Failed to execute ‘postMesage’ on ‘DOMWindow’: The target origin provided (‘https://chat-widget.papercups.io’) does not match the recipient window’s origin (‘https://studio.iterative.ai’).

**Comment by mvshmakov** [comment]
@haimat, thanks for the report, we're on it!

@mjasion, could you please take a look at this?

**Comment by mvshmakov** [comment]
@haimat thanks for the report, chat window will be working in an hour. Let us know if it does not.

**Comment by haimat** [comment]
It's working now, thanks a lot :+1:
