### ISSUE TITLE
Metric or plot files missing from DVC project

### ISSUE THREAD

**Issue by haimat** [iterative/studio-support#71]
I just started out with Studio and imported one of our DVC porjects. Import from Github went fine, then I added the credentials to the project's default remote. This also seems to have worked, however, I get the message "Missing 9 metric or plot file(s) in 9 commit(s)". I don't know about these missing files, but Studio does not tell me more. What can I do?

![image](https://user-images.githubusercontent.com/6633976/219387679-8d1358d6-933f-4389-91f8-f6fbe9ae214a.png)

btw. I tried the "force import" option, but without luck.

**Comment by tapadipti** [comment]
@haimat When you open the project, do you see any data missing in any of the commits in the project table?

**Comment by haimat** [comment]
@tapadipti Well, it seems previous commits were missing some files, because of some issues with our DVC configuration. But this should be fixed now, the latest commits don't have the exclamation mark in Studio any more. How can I get rid of that warning message?

**Comment by tapadipti** [comment]
@amritghimire Can we make this warning closable?

**Comment by amritghimire** [comment]
@tapadipti It is already closable due to recent changes.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/16842655/219633528-417c0bba-2a9b-4985-8d0c-a22fbde3c69e.png">

**Comment by haimat** [comment]
I solved this be creating a new Github repo for this project and starting with DVC there from scratch ...
