### ISSUE TITLE
Filter commits by commit message

### ISSUE THREAD

**Issue by dberenbaum** [iterative/studio-support#74]
I would like to be able to filter which commits are shown based on the commit message, similar to how I can filter branches by name.

Internal Slack link for more context: https://iterativeai.slack.com/archives/C03JS2V4MQU/p1676908095570189

**Comment by jellebouwman** [comment]
Makes sense to support this! I've started work on this and will report back when we've implemented this.

**Comment by jellebouwman** [comment]
@dberenbaum - @mvshmakov pointed out that in the meantime, users can the `Search` option to search commits on their commit message, sha, or other name. We'll figure out if we need to re-adjust this section in an internal ticket.

<img width="546" alt="221153640-aee004f2-d284-4a14-a16c-3fdde22bb48d" src="https://user-images.githubusercontent.com/32744870/221155782-fbd89be8-2595-4cb2-9689-7c15bc19bff3.png">

**Comment by dberenbaum** [comment]
@jellebouwman Feel free to close in favor of the internal ticket.

**Comment by jellebouwman** [comment]
Yesterday's release added the `Commit message` filter to Studio - closing this!

<img width="1406" alt="Screenshot 2023-02-28 at 09 45 55" src="https://user-images.githubusercontent.com/32744870/221800494-d4f49cfa-df97-4dfd-8f85-3666e4388c7d.png">
