### ISSUE TITLE
How can a dev pushing to the repo provide his Studio token to the Github action for CML?

### ISSUE THREAD

**Issue by haimat** [iterative/studio-support#84]
We use DML to run experiments via Github runners, and DVCLive to monitor them in real time via Studio. For that one needs to generate and provide a personal token in Studio and pass that to DVCLive via the Github workflow. This works fine with one developer and one Studio token. But what if there are different devs with different Studio tokens - how can the dev which pushes something to the Github repo provide his own personal Studio token to the Github action?

Edit: As an alternative - probably even the better solution - I could provide one single Studio token for our team as Github secret. Hoewever, I haven't found a way to create a token for a team in Studio, only for me as user. Is there an option to create one token for the whole team in Studio?

**Comment by shcheklein** [comment]
@tapadipti could we summarize the internal discussion and the chat thread here please?

**Comment by tapadipti** [comment]
For now, you could use one of the team members’ token. To avoid using a personal token, you can create a dedicated (GitHub) bot account and issue it a Studio token. Then add the bot to the team and use its token for live experiments.

@haimat This unblocks you for now, right? If yes, we can close this issue.

With team-level tokens (if we support it), a concern is that identifying the commit author can be tricky. This is a separate discussion. One possibility is to support an additional field `AUTHOR_EMAIL` in the live events.

**Comment by haimat** [comment]
@tapadipti Yes thanks, using one team member's token for the whole team works for us now :+1:
