### ISSUE TITLE
New model never leaves "queued" state

### ISSUE THREAD

**Issue by haimat** [iterative/studio-support#86]
I have the same issue as last time - after adding a new model in Studio it never gets past the "queued" state:

![image](https://github.com/iterative/studio-support/assets/6633976/74870f61-1f8d-4669-b500-11de27e9770b)

Even after hours nothing changes. 
What can I do?

**Comment by shcheklein** [comment]
Looking into this. Can you for now share the screen that you use to add a model - is it a branch, direct commit, etc?

**Comment by shcheklein** [comment]
Okay, a quick update - I see the message in logs: `failed to push some refs to 'https://github.com/***/***`, `[remote rejected] (protected branch hook declined)`. Are you by chance trying to push the model right into the `main` branch that is protected (requires a PR)? Can you try to create a branch please?

@aguschin we need a better way to handle these errors in the MR. It's the second time that we get this (that we know about) and it's quite confusing. wdyt?

**Comment by aguschin** [comment]
@shcheklein, sure. I'd expect getting an error here TBH, like we usually get when adding a model fails. I suppose the action failed, but FE wasn't able to fetch it? I guess we can reproduce and see.

**Comment by haimat** [comment]
Yes I was trying to push to `main`. Do I always need to manually create a PR for a new model first?

**Comment by shcheklein** [comment]
@haimat 

> Do I always need to manually create a PR for a new model first?

No, not at all. But if that branch is protected on GH (an option set that you can't commit directly w/o a PR into it), there is nothing we can do then- we have to obey the GH rules.

**Comment by amritghimire** [comment]
@haimat We have updated something in studio to provide you with proper error message when you try to push to a protected branch. 

Unfortunately, as @shcheklein mentioned, we won't be able to push to the protected branch as per GitHub rules.

**Comment by amritghimire** [comment]
Closing this. Feel free to reopen this or open a new issue if you have any issue further.
