### ISSUE TITLE
5000 column limit

### ISSUE THREAD

**Issue by slevang** [iterative/studio-support#87]
I'm running into an issue with a repo where recently added metrics and params files are not being detected in the columns view of Studio. 

The issue seems to be that at one point in the commit history, we had a huge number of metrics dumped (~10000) since we are operating in a large multi-dimensional space. I noticed that the counter on the columns settings page seems to top out at 5000. Testing this behavior with a toy repo, I confirmed that studio stops parsing columns >5000, and that if I make a new squashed version of our repo, Studio picks up the desired columns just fine.

We've since pared the metrics back greatly in the main repo, but Studio still won't pick up the desired columns because it is holding on to the old ones.

Any thoughts on how to recover from this, short of squashing the entire commit history?

**Comment by shcheklein** [comment]
hey, let us confirm this. I think it should be prioritizing the latest metrics above the oldest ones.

Could you for now try to reparse it:

<img width="481" alt="Screenshot 2023-05-23 at 11 43 52 AM" src="https://github.com/iterative/studio-support/assets/3659196/2fab5f30-d30c-411a-af99-f3781893095b">

The `Force Import` option.

**Comment by slevang** [comment]
Yeah, have tried `Force Import` and even delete and recreate the project a couple times. Is there an expected ordering of branches in the parsing, i.e. latest vs default?

I did try this in a test repo and was able to get the latest metrics/params to show again after exceeding the 5000 limit in a prior commit. And as mentioned I did get everything showing by squashing commits and making a new copied repo. So something unexpected in the branch order parsing is all I can think of.

Related question, is there any particular reason to limit metrics in Studio?

**Comment by slevang** [comment]
Any further suggestions for this issue?

**Comment by shcheklein** [comment]
@slevang sorry for the delay. I think we've expanded the limit and it should be deployed now. Could you try to force reparse the project? (force import). Also, separately, we are looking into why the new metrics were not prioritized. We'll keep you updated here.

**Comment by slevang** [comment]
Yes it works now, thank you!

This can be closed from my side, but feel free to leave open if you're still investigating the prioritization order.

**Comment by tapadipti** [comment]
@slevang Thanks for confirming.
I'm closing this issue. But we have an internal issue to investigate the prioritization order and we will comment here once there is an update.
