### ISSUE TITLE
Azure Blob connection in Studio

### ISSUE THREAD

**Issue by KoveshnikovS** [iterative/studio-support#89]
When trying to connect Azure Blob in Studio a warning appears: No permission to fetch remote data Set credentials, or Force import. The connection string is copied from DVC add-on of VS Code, where it's working fine.

**Comment by shcheklein** [comment]
For the record I've reproduced this. It's a bug in `dvc-azure` plugin when it runs in a Docker environment. I'll try to do a PR / workaround soon and give more details. Thanks @KoveshnikovS for the report!

**Comment by shcheklein** [comment]
@KoveshnikovS thanks for the report! The fix should be deployed soon.
